sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t desenvolvimento docker-image/

script:
  - docker run -t -it -v $PWD:/base_dir desenvolvimento bash -c "cd /base_dir && python preprocessor.py test"
